### ISSUE TITLE
Superposición de botón

### ISSUE THREAD

**Issue by Nidev-lab** [MRieznik/RestoCodeFront#20]
## Proceso

1. Ingrese a la pagina.
2. Quise registrarme con un nuevo usuario.

## Resultado esperado

•  Encontrar un formulario de registro sin ningún tipo de superposición.

## Resultado actual

• El boton "Registrarse" se superpone al footer.

## Captura

![image](https://github.com/MRieznik/RestoCodeFront/assets/53904695/f096c2bf-e9e7-4d8a-9882-bce61720a2fe)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MRieznik** [comment]
Buenas noches Nico, problema solucionado, saludos.

**Comment by MRieznik** [comment]
Procedo a cerrarla

**Comment by Nidev-lab** [comment]
Buenas! Chicos tienen un user admin? Si pudieran pasarmelo estaria joya.

**Comment by MRieznik** [comment]
Sip, ahi te dejo mi usuario que esta como admin.
Mail: m.rieznik17@gmail.com
Contraseña: marcos1234
